// <auto-generated />
using Kladionica.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kladionica.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Kladionica.Models.Ticket", b =>
                {
                    b.Property<string>("SelectedOutcome")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("string")
                        .UseIdentityColumn();

                    b.Property<int>("Payment")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("SelectedOutcome");

                    b.ToTable("SelectedOutcome");
                });
#pragma warning restore 612, 618
        }
    }
}
